date.timezone = Asia/Ho_Chi_Minh
display_errors = Off
log_errors = On
expose_php = Off
upload_max_filesize = 32M
post_max_size = 32M
session.cookie_httponly = 1
session.cookie_samesite = Lax
disable_functions = exec,passthru,shell_exec,system,proc_open,popen
